package SistemaGestorActivos.Logic;
// Generated 19-mar-2019 19:56:13 by Hibernate Tools 4.3.1



/**
 * Activo generated by hbm2java
 */
public class Activo  implements java.io.Serializable {


     private Integer codigo;
     private Bien bien;
     private Categoria categoria;
     private Labora labora;

    public Activo() {
    }

    public Activo(Bien bien, Categoria categoria, Labora labora) {
       this.bien = bien;
       this.categoria = categoria;
       this.labora = labora;
    }
   
    public Integer getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }
    public Bien getBien() {
        return this.bien;
    }
    
    public void setBien(Bien bien) {
        this.bien = bien;
    }
    public Categoria getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(Categoria categoria) {
        this.categoria = categoria;
    }
    public Labora getLabora() {
        return this.labora;
    }
    
    public void setLabora(Labora labora) {
        this.labora = labora;
    }




}


