package SistemaGestorActivos.Logic;
// Generated 19-abr-2019 17:06:01 by Hibernate Tools 4.3.1



/**
 * Activo generated by hbm2java
 */
public class Activo  implements java.io.Serializable {


     private Integer id;
     private Bien bien;
     private Categoria categoria;
     private Funcionario funcionario;

    public Activo() {
    }

    public Activo(Bien bien, Categoria categoria, Funcionario funcionario) {
       this.bien = bien;
       this.categoria = categoria;
       this.funcionario = funcionario;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Bien getBien() {
        return this.bien;
    }
    
    public void setBien(Bien bien) {
        this.bien = bien;
    }
    public Categoria getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(Categoria categoria) {
        this.categoria = categoria;
    }
    public Funcionario getFuncionario() {
        return this.funcionario;
    }
    
    public void setFuncionario(Funcionario funcionario) {
        this.funcionario = funcionario;
    }




}


