package SistemaGestorActivos.Logic;
// Generated 31-may-2019 22:51:55 by Hibernate Tools 4.3.1



/**
 * Activo generated by hbm2java
 */
public class Activo  implements java.io.Serializable {


     private Integer id;
     private Bien bien;
     private Categoria categoria;
     private Funcionario funcionario;
     private int consecutivoActual;

    public Activo() {
    }

	
    public Activo(Bien bien, Categoria categoria, int consecutivoActual) {
        this.bien = bien;
        this.categoria = categoria;
        this.consecutivoActual = consecutivoActual;
    }
    public Activo(Bien bien, Categoria categoria, Funcionario funcionario, int consecutivoActual) {
       this.bien = bien;
       this.categoria = categoria;
       this.funcionario = funcionario;
       this.consecutivoActual = consecutivoActual;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Bien getBien() {
        return this.bien;
    }
    
    public void setBien(Bien bien) {
        this.bien = bien;
    }
    public Categoria getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(Categoria categoria) {
        this.categoria = categoria;
    }
    public Funcionario getFuncionario() {
        return this.funcionario;
    }
    
    public void setFuncionario(Funcionario funcionario) {
        this.funcionario = funcionario;
    }
    public int getConsecutivoActual() {
        return this.consecutivoActual;
    }
    
    public void setConsecutivoActual(int consecutivoActual) {
        this.consecutivoActual = consecutivoActual;
    }




}


