package SistemaGestorActivos.Logic;
// Generated 19-mar-2019 19:56:13 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Bien generated by hbm2java
 */
public class Bien  implements java.io.Serializable {


     private Integer codigo;
     private Solicitud solicitud;
     private String marca;
     private double precio;
     private int cantidad;
     private String descripcion;
     private String modelo;
     private Set<Activo> activos = new HashSet<Activo>(0);

    public Bien() {
    }

	
    public Bien(String marca, double precio, int cantidad, String descripcion, String modelo) {
        this.marca = marca;
        this.precio = precio;
        this.cantidad = cantidad;
        this.descripcion = descripcion;
        this.modelo = modelo;
    }
    public Bien(Solicitud solicitud, String marca, double precio, int cantidad, String descripcion, String modelo, Set<Activo> activos) {
       this.solicitud = solicitud;
       this.marca = marca;
       this.precio = precio;
       this.cantidad = cantidad;
       this.descripcion = descripcion;
       this.modelo = modelo;
       this.activos = activos;
    }
   
    public Integer getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }
    public Solicitud getSolicitud() {
        return this.solicitud;
    }
    
    public void setSolicitud(Solicitud solicitud) {
        this.solicitud = solicitud;
    }
    public String getMarca() {
        return this.marca;
    }
    
    public void setMarca(String marca) {
        this.marca = marca;
    }
    public double getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(double precio) {
        this.precio = precio;
    }
    public int getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getModelo() {
        return this.modelo;
    }
    
    public void setModelo(String modelo) {
        this.modelo = modelo;
    }
    public Set<Activo> getActivos() {
        return this.activos;
    }
    
    public void setActivos(Set<Activo> activos) {
        this.activos = activos;
    }




}


