package SistemaGestorActivos.Logic;
// Generated 24-mar-2019 18:06:35 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Dependencia generated by hbm2java
 */
public class Dependencia  implements java.io.Serializable {


     private int id;
     private Funcionario funcionario;
     private String nombre;
     private Set<Solicitud> solicituds = new HashSet<Solicitud>(0);

    public Dependencia() {
    }

	
    public Dependencia(int id, String nombre) {
        this.id = id;
        this.nombre = nombre;
    }
    public Dependencia(int id, Funcionario funcionario, String nombre, Set<Solicitud> solicituds) {
       this.id = id;
       this.funcionario = funcionario;
       this.nombre = nombre;
       this.solicituds = solicituds;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Funcionario getFuncionario() {
        return this.funcionario;
    }
    
    public void setFuncionario(Funcionario funcionario) {
        this.funcionario = funcionario;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set<Solicitud> getSolicituds() {
        return this.solicituds;
    }
    
    public void setSolicituds(Set<Solicitud> solicituds) {
        this.solicituds = solicituds;
    }




}


