package SistemaGestorActivos.Logic;
// Generated 19-mar-2019 19:56:13 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Dependencia generated by hbm2java
 */
public class Dependencia  implements java.io.Serializable {


     private String codigo;
     private Funcionario funcionario;
     private String nombreDep;
     private Set<Labora> laboras = new HashSet<Labora>(0);
     private Set<Solicitud> solicituds = new HashSet<Solicitud>(0);

    public Dependencia() {
    }

	
    public Dependencia(String codigo, String nombreDep) {
        this.codigo = codigo;
        this.nombreDep = nombreDep;
    }
    public Dependencia(String codigo, Funcionario funcionario, String nombreDep, Set<Labora> laboras, Set<Solicitud> solicituds) {
       this.codigo = codigo;
       this.funcionario = funcionario;
       this.nombreDep = nombreDep;
       this.laboras = laboras;
       this.solicituds = solicituds;
    }
   
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public Funcionario getFuncionario() {
        return this.funcionario;
    }
    
    public void setFuncionario(Funcionario funcionario) {
        this.funcionario = funcionario;
    }
    public String getNombreDep() {
        return this.nombreDep;
    }
    
    public void setNombreDep(String nombreDep) {
        this.nombreDep = nombreDep;
    }
    public Set<Labora> getLaboras() {
        return this.laboras;
    }
    
    public void setLaboras(Set<Labora> laboras) {
        this.laboras = laboras;
    }
    public Set<Solicitud> getSolicituds() {
        return this.solicituds;
    }
    
    public void setSolicituds(Set<Solicitud> solicituds) {
        this.solicituds = solicituds;
    }




}


