package SistemaGestorActivos.Logic;
// Generated 29-may-2019 18:47:09 by Hibernate Tools 4.3.1



/**
 * Erazon generated by hbm2java
 */
public class Erazon  implements java.io.Serializable {


     private int idSolicitud;
     private Estado estado;
     private Solicitud solicitud;
     private String comentario;

    public Erazon() {
    }

    public Erazon(Estado estado, Solicitud solicitud, String comentario) {
       this.estado = estado;
       this.solicitud = solicitud;
       this.comentario = comentario;
    }
   
    public int getIdSolicitud() {
        return this.idSolicitud;
    }
    
    public void setIdSolicitud(int idSolicitud) {
        this.idSolicitud = idSolicitud;
    }
    public Estado getEstado() {
        return this.estado;
    }
    
    public void setEstado(Estado estado) {
        this.estado = estado;
    }
    public Solicitud getSolicitud() {
        return this.solicitud;
    }
    
    public void setSolicitud(Solicitud solicitud) {
        this.solicitud = solicitud;
    }
    public String getComentario() {
        return this.comentario;
    }
    
    public void setComentario(String comentario) {
        this.comentario = comentario;
    }




}


