package SistemaGestorActivos.Logic;
// Generated 19-mar-2019 19:56:13 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Funcionario generated by hbm2java
 */
public class Funcionario  implements java.io.Serializable {


     private String id;
     private String nombre;
     private Set<Usuario> usuarios = new HashSet<Usuario>(0);
     private Set<Labora> laboras = new HashSet<Labora>(0);
     private Set<Solicitud> solicituds = new HashSet<Solicitud>(0);
     private Set<Dependencia> dependencias = new HashSet<Dependencia>(0);

    public Funcionario() {
    }

	
    public Funcionario(String id, String nombre) {
        this.id = id;
        this.nombre = nombre;
    }
    public Funcionario(String id, String nombre, Set<Usuario> usuarios, Set<Labora> laboras, Set<Solicitud> solicituds, Set<Dependencia> dependencias) {
       this.id = id;
       this.nombre = nombre;
       this.usuarios = usuarios;
       this.laboras = laboras;
       this.solicituds = solicituds;
       this.dependencias = dependencias;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set<Usuario> getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set<Usuario> usuarios) {
        this.usuarios = usuarios;
    }
    public Set<Labora> getLaboras() {
        return this.laboras;
    }
    
    public void setLaboras(Set<Labora> laboras) {
        this.laboras = laboras;
    }
    public Set<Solicitud> getSolicituds() {
        return this.solicituds;
    }
    
    public void setSolicituds(Set<Solicitud> solicituds) {
        this.solicituds = solicituds;
    }
    public Set<Dependencia> getDependencias() {
        return this.dependencias;
    }
    
    public void setDependencias(Set<Dependencia> dependencias) {
        this.dependencias = dependencias;
    }




}


