package SistemaGestorActivos.Logic;
// Generated 29-may-2019 18:47:09 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Puesto generated by hbm2java
 */
public class Puesto  implements java.io.Serializable {


     private int id;
     private String descripcion;
     private Set<Funcionario> funcionarios = new HashSet<Funcionario>(0);

    public Puesto() {
    }

	
    public Puesto(int id, String descripcion) {
        this.id = id;
        this.descripcion = descripcion;
    }
    public Puesto(int id, String descripcion, Set<Funcionario> funcionarios) {
       this.id = id;
       this.descripcion = descripcion;
       this.funcionarios = funcionarios;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set<Funcionario> getFuncionarios() {
        return this.funcionarios;
    }
    
    public void setFuncionarios(Set<Funcionario> funcionarios) {
        this.funcionarios = funcionarios;
    }




}


