package SistemaGestorActivos.Logic;
// Generated 19-mar-2019 19:56:13 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Solicitud generated by hbm2java
 */
public class Solicitud  implements java.io.Serializable {


     private Integer numero;
     private Dependencia dependencia;
     private Funcionario funcionario;
     private String estado;
     private Date fecha;
     private String tipoAdquisicion;
     private int cantidad;
     private double monto;
     private String comprobante;
     private Set<Bien> biens = new HashSet<Bien>(0);

    public Solicitud() {
    }

	
    public Solicitud(String estado, Date fecha, String tipoAdquisicion, int cantidad, double monto, String comprobante) {
        this.estado = estado;
        this.fecha = fecha;
        this.tipoAdquisicion = tipoAdquisicion;
        this.cantidad = cantidad;
        this.monto = monto;
        this.comprobante = comprobante;
    }
    public Solicitud(Dependencia dependencia, Funcionario funcionario, String estado, Date fecha, String tipoAdquisicion, int cantidad, double monto, String comprobante, Set<Bien> biens) {
       this.dependencia = dependencia;
       this.funcionario = funcionario;
       this.estado = estado;
       this.fecha = fecha;
       this.tipoAdquisicion = tipoAdquisicion;
       this.cantidad = cantidad;
       this.monto = monto;
       this.comprobante = comprobante;
       this.biens = biens;
    }
   
    public Integer getNumero() {
        return this.numero;
    }
    
    public void setNumero(Integer numero) {
        this.numero = numero;
    }
    public Dependencia getDependencia() {
        return this.dependencia;
    }
    
    public void setDependencia(Dependencia dependencia) {
        this.dependencia = dependencia;
    }
    public Funcionario getFuncionario() {
        return this.funcionario;
    }
    
    public void setFuncionario(Funcionario funcionario) {
        this.funcionario = funcionario;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public String getTipoAdquisicion() {
        return this.tipoAdquisicion;
    }
    
    public void setTipoAdquisicion(String tipoAdquisicion) {
        this.tipoAdquisicion = tipoAdquisicion;
    }
    public int getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }
    public double getMonto() {
        return this.monto;
    }
    
    public void setMonto(double monto) {
        this.monto = monto;
    }
    public String getComprobante() {
        return this.comprobante;
    }
    
    public void setComprobante(String comprobante) {
        this.comprobante = comprobante;
    }
    public Set<Bien> getBiens() {
        return this.biens;
    }
    
    public void setBiens(Set<Bien> biens) {
        this.biens = biens;
    }




}


